# This is a basic workflow that is manually triggered
name: Build

# Controls when the action will run. Workflow runs when manually triggered using the UI
# or API.
on:
  workflow_dispatch:
  push:
    branches:
      -  main

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  build:
    name: npm install and build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2.3.3
      - name: prepare
        uses: DerYeger/yarn-setup-action@master
        with:
          node-version: 16
      - run: yarn install
      - run: yarn run build --if-present
      - uses: codacy/codacy-coverage-reporter-action@master
        with:
          project-token: ${{ secrets.CODACY_PROJECT_TOKEN }}
          coverage-reports: dist/coverage/lcov.info
